USE [master]
GO

/****** Object:  Database [catalog]    Script Date: 04/10/2016 13:56:42 ******/
CREATE DATABASE [catalog] ON  PRIMARY 
( NAME = N'catalog_Data', FILENAME = N'C:\LocalTDDbookDatabase\catalog_data.mdf' , SIZE = 1984KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'catalog_Log', FILENAME = N'C:\LocalTDDbookDatabase\catalog_log.ldf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [catalog] SET COMPATIBILITY_LEVEL = 80
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [catalog].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [catalog] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [catalog] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [catalog] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [catalog] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [catalog] SET ARITHABORT OFF 
GO

ALTER DATABASE [catalog] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [catalog] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [catalog] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [catalog] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [catalog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [catalog] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [catalog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [catalog] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [catalog] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [catalog] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [catalog] SET  ENABLE_BROKER 
GO

ALTER DATABASE [catalog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [catalog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [catalog] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [catalog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [catalog] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [catalog] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [catalog] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [catalog] SET  READ_WRITE 
GO

ALTER DATABASE [catalog] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [catalog] SET  MULTI_USER 
GO

ALTER DATABASE [catalog] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [catalog] SET DB_CHAINING OFF 
GO

