//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace ServiceGateway {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CatalogGatewaySoap", Namespace="http://nunit.org/services")]
    public class CatalogGateway : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public CatalogGateway() {
            this.Url = "http://localhost/ServiceInterface/CatalogServiceInterface.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://nunit.org/services/FindByRecordingId", RequestNamespace="http://nunit.org/services", ResponseNamespace="http://nunit.org/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Recording", Namespace="http://nunit.org/webservices")]
        public RecordingDto FindByRecordingId(long id) {
            object[] results = this.Invoke("FindByRecordingId", new object[] {
                        id});
            return ((RecordingDto)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFindByRecordingId(long id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FindByRecordingId", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public RecordingDto EndFindByRecordingId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RecordingDto)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nunit.org/webservices")]
    public class RecordingDto {
        
        /// <remarks/>
        public long id;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string artistName;
        
        /// <remarks/>
        public string releaseDate;
        
        /// <remarks/>
        public string labelName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tracks")]
        public TrackDto[] tracks;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reviews")]
        public ReviewDto[] reviews;
        
        /// <remarks/>
        public int totalRunTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalRunTimeSpecified;
        
        /// <remarks/>
        public int averageRating;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool averageRatingSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nunit.org/webservices")]
    public class TrackDto {
        
        /// <remarks/>
        public long id;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string artistName;
        
        /// <remarks/>
        public int duration;
        
        /// <remarks/>
        public string genreName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nunit.org/webservices")]
    public class ReviewDto {
        
        /// <remarks/>
        public long id;
        
        /// <remarks/>
        public string reviewerName;
        
        /// <remarks/>
        public int rating;
        
        /// <remarks/>
        public string reviewContent;
    }
}
