//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
// 
namespace ServiceGateway {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CatalogGatewaySoap", Namespace="http://nunit.org/services")]
    public class CatalogGateway : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public CatalogGateway() {
            this.Url = "http://localhost/ServiceInterface/CatalogServiceInterface.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://nunit.org/services/FindByRecordingId", RequestNamespace="http://nunit.org/services", ResponseNamespace="http://nunit.org/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Recording", Namespace="http://nunit.org/webservices")]
        public RecordingDto FindByRecordingId(long id) {
            object[] results = this.Invoke("FindByRecordingId", new object[] {
                        id});
            return ((RecordingDto)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFindByRecordingId(long id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FindByRecordingId", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public RecordingDto EndFindByRecordingId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RecordingDto)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://nunit.org/services/AddReview", RequestNamespace="http://nunit.org/services", ResponseNamespace="http://nunit.org/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReviewDto AddReview(string reviewerName, string content, int rating, long recordingId) {
            object[] results = this.Invoke("AddReview", new object[] {
                        reviewerName,
                        content,
                        rating,
                        recordingId});
            return ((ReviewDto)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddReview(string reviewerName, string content, int rating, long recordingId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddReview", new object[] {
                        reviewerName,
                        content,
                        rating,
                        recordingId}, callback, asyncState);
        }
        
        /// <remarks/>
        public ReviewDto EndAddReview(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReviewDto)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://nunit.org/services/DeleteReview", RequestNamespace="http://nunit.org/services", ResponseNamespace="http://nunit.org/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteReview(long reviewId) {
            this.Invoke("DeleteReview", new object[] {
                        reviewId});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteReview(long reviewId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteReview", new object[] {
                        reviewId}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndDeleteReview(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nunit.org/webservices")]
    public class RecordingDto {
        
        /// <remarks/>
        public long id;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string artistName;
        
        /// <remarks/>
        public string releaseDate;
        
        /// <remarks/>
        public string labelName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tracks")]
        public TrackDto[] tracks;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reviews")]
        public ReviewDto[] reviews;
        
        /// <remarks/>
        public string totalRunTime;
        
        /// <remarks/>
        public int averageRating;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nunit.org/webservices")]
    public class TrackDto {
        
        /// <remarks/>
        public long id;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string artistName;
        
        /// <remarks/>
        public string duration;
        
        /// <remarks/>
        public string genreName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nunit.org/webservices")]
    public class ReviewDto {
        
        /// <remarks/>
        public long id;
        
        /// <remarks/>
        public string reviewerName;
        
        /// <remarks/>
        public int rating;
        
        /// <remarks/>
        public string reviewContent;
    }
}
