INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (1, 1, 1, 2, N'Just OK')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (2, 1, 2, 5, N'Really cool stuff. These guys rock!')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (3, 2, 1, 5, N'Loved them. Very energetic.')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (4, 2, 2, 1, N'Why did they even release this junk?')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (5, 2, 3, 5, N'They rule!')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (7, 3, 3, 5, N'This is the best CD I own')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (9495, 5704, 9779, 3, N'Fake Review Content')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (9496, 5704, 9780, 3, N'Fake Review Content')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (9498, 5704, 9782, 3, N'Fake Review Content')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (9499, 5704, 9783, 3, N'Fake Review Content')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (9500, 5704, 9784, 3, N'Fake Review Content')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (9501, 5704, 9785, 3, N'Fake Review Content')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (9502, 5704, 9791, 3, N'Fake Review Content')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (9503, 5704, 9792, 3, N'Fake Review Content')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (9536, 5704, 9828, 3, N'Fake Review Content')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (9537, 5704, 9829, 3, N'Fake Review Content')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (100001, 100001, 100001, 1, N'Inspiration was low')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (100002, 100002, 100001, 3, N'Could be better')
INSERT INTO [dbo].[Review] ([id], [reviewerid], [recordingid], [rating], [review]) VALUES (100003, 100003, 100001, 4, N'I thought it was great')
