INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (45, N'Lonesome Day', 248, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (46, N'Into The Fire', 304, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (47, N'Waitin'' On A Sunny Day', 258, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (48, N'The Nothing Man', 263, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (49, N'Countin'' On A Miracle', 284, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (50, N'Empty Sky', 214, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (51, N'Worlds Apart', 367, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (52, N'Let''s Be Friends', 261, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (53, N'Further On (Up The Road)', 232, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (54, N'The Fuse', 337, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (55, N'Mary''s Place', 363, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (56, N'You''re Missing', 311, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (57, N'The Rising', 290, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (58, N'Paradise', 339, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (59, N'My City Of Ruins', 300, 1, 4, 4)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (100001, N'Track #1', 60, 100001, 100001, 100001)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (100002, N'Track #2', 120, 100001, 100001, 100001)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (100003, N'Track #3', 180, 100001, 100001, 100001)
INSERT INTO [dbo].[Track] ([id], [title], [duration], [genreid], [artistid], [recordingid]) VALUES (100004, N'Track #4', 240, 100001, 100001, 100001)
